import crypto from 'node:crypto';
import { Router } from 'express';
import type { Request, Response } from 'express';
import { serviceClient } from '../../supabase.js';
import { claimEvent, persistInbound } from '../../services/inbound.js';
import { dispatchInbound } from '../../services/dispatch.js';
import type { InboundMedia, NormalizedInboundEvent } from '../../channels/meta/types.js';

export const telegramWebhookRouter = Router();

/**
 * Telegram's inbound webhook.
 *
 * Telegram used to post straight to n8n, which meant the customer's message was
 * only recorded after the agent had already answered it, and that nothing in
 * this application ever saw a Telegram message. Both facts had consequences:
 * a conversation staff had taken over recorded nothing, and Shwari could not be
 * reached on the one channel every tenant already has.
 *
 * So Telegram now arrives here and follows exactly the path web chat and Meta
 * follow — resolve, claim, persist, dispatch. The n8n sales pipeline is still
 * what answers a customer; it is simply called from dispatch rather than being
 * the front door.
 *
 * Authentication is Telegram's secret header, matched against the channel's own
 * secret_token. That is what maps an update to one tenant, and it is the same
 * mechanism the n8n workflow used, so existing bots keep working.
 */
telegramWebhookRouter.post('/webhooks/telegram', (req: Request, res: Response) => {
  const presented = req.headers['x-telegram-bot-api-secret-token'];
  if (typeof presented !== 'string' || !presented) {
    return res.sendStatus(401);
  }

  // Ack first. Telegram retries anything that is not a prompt 200, and an AI
  // turn takes far longer than it is willing to wait.
  res.sendStatus(200);

  void handleUpdate(presented, req.body).catch((e) => {
    console.error('[webhooks/telegram] processing failed:', e instanceof Error ? e.message : e);
  });
});

async function handleUpdate(presentedSecret: string, body: unknown): Promise<void> {
  const channel = await resolveBySecret(presentedSecret);
  if (!channel) {
    console.warn('[webhooks/telegram] rejected: no active channel matches that secret');
    return;
  }

  const event = parseUpdate(body, channel.tenantId, channel.id);
  if (!event) return;

  const claimed = await claimEvent('telegram', event.messageId, event.tenantId, event.channelId);
  if (!claimed) {
    console.log('[webhooks/telegram] duplicate delivery; already handled');
    return;
  }

  const stored = await persistInbound(event);
  if (!stored) return;

  if (!stored.aiEnabled) {
    console.log(`[webhooks/telegram] conversation ${stored.conversationId} is staff-handled; no AI reply`);
    return;
  }

  await dispatchInbound(event, channel, stored.conversationId);
}

/**
 * Find the channel whose secret this is.
 *
 * The comparison is constant-time and happens after the row is fetched by
 * secret, so a lookup that returns nothing and one that returns a mismatched
 * row take the same shape. The secret is high-entropy and generated by us, so
 * an equality lookup is safe; the extra check guards against a database that
 * compared loosely.
 */
async function resolveBySecret(presented: string) {
  const { data } = await serviceClient
    .from('channels')
    .select('id, tenant_id, channel_type, secret_token, status')
    .eq('channel_type', 'telegram')
    .eq('secret_token', presented)
    .maybeSingle();

  if (!data || data.status !== 'active' || !data.secret_token) return null;
  if (!timingSafeEqual(data.secret_token, presented)) return null;

  return {
    id: data.id,
    tenantId: data.tenant_id,
    channelType: 'telegram' as const,
    secretToken: data.secret_token,
    status: data.status,
  };
}

function timingSafeEqual(a: string, b: string): boolean {
  const ab = Buffer.from(a, 'utf8');
  const bb = Buffer.from(b, 'utf8');
  if (ab.length !== bb.length) return false;
  return crypto.timingSafeEqual(ab, bb);
}

/**
 * A Telegram update, reduced to the one shape the rest of the system speaks.
 *
 * Only plain messages are handled. Edits, channel posts and callbacks are
 * silently ignored rather than treated as new customer messages.
 */
export function parseUpdate(
  body: unknown,
  tenantId: string,
  channelId: string
): NormalizedInboundEvent | null {
  const update = body as any;
  const message = update?.message;
  if (!message || typeof message !== 'object') return null;

  const chatId = message.chat?.id;
  if (chatId === undefined || chatId === null) return null;

  const text = typeof message.text === 'string' ? message.text : null;
  const media = mediaOf(message);
  if (!text && !media) return null;

  const from = message.from ?? {};
  const name = [from.first_name, from.last_name].filter(Boolean).join(' ').trim();

  return {
    tenantId,
    channelId,
    channelType: 'telegram',
    customerId: String(chatId),
    customerName: name || (from.username ? `@${from.username}` : null),
    // update_id is unique per bot, but message_id is what identifies the
    // message itself, and a retried delivery reuses it.
    messageId: `${chatId}:${message.message_id}`,
    text,
    media,
    timestamp: message.date
      ? new Date(message.date * 1000).toISOString()
      : new Date().toISOString(),
  };
}

function mediaOf(message: any): NormalizedInboundEvent['media'] {
  const caption = typeof message.caption === 'string' ? message.caption : null;

  const found: Array<[InboundMedia['kind'], any]> = [
    // Telegram sends a photo as an array of sizes, largest last.
    ['image', Array.isArray(message.photo) ? message.photo[message.photo.length - 1] : null],
    ['audio', message.voice ?? message.audio],
    ['video', message.video],
    ['document', message.document],
    ['sticker', message.sticker],
  ];

  for (const [kind, value] of found) {
    if (value?.file_id) {
      return {
        kind,
        mediaId: String(value.file_id),
        mimeType: typeof value.mime_type === 'string' ? value.mime_type : null,
        caption,
      };
    }
  }
  return null;
}
