-- ==============================================================================
-- SHWARI iPHONES WHATSAPP AGENT - FLEXIBLE FORMAT SCHEMA
-- ==============================================================================

-- 1. DROP EXISTING TABLES
DROP TABLE IF EXISTS public.general_pricelist;
DROP TABLE IF EXISTS public.lipa_mdogo_mdogo;

-- ------------------------------------------------------------------------------
-- 2. Create Tables with TEXT columns for Prices to support "Ksh 10,000" formats
-- ------------------------------------------------------------------------------

CREATE TABLE public.general_pricelist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Phone Model" TEXT NOT NULL,
    "Specs" TEXT,
    "Cash Price" TEXT NOT NULL,
    "Deposit" TEXT,
    "3 Months Plan" TEXT,
    "12 Weeks" TEXT,
    "Deposit_1" TEXT,
    "6 Months Plan" TEXT,
    "24 Weeks" TEXT,
    availability BOOLEAN DEFAULT TRUE,
    notes TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.lipa_mdogo_mdogo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Phone Model" TEXT NOT NULL,
    "Specs" TEXT,
    "Cash Price" TEXT NOT NULL,
    "Deposit" TEXT,
    "3 Months Plan" TEXT,
    "12 Weeks" TEXT,
    "Deposit_1" TEXT,
    "6 Months Plan" TEXT,
    "24 Weeks" TEXT,
    availability BOOLEAN DEFAULT TRUE,
    notes TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.general_pricelist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lipa_mdogo_mdogo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access" ON public.general_pricelist FOR ALL USING (true);
CREATE POLICY "Enable all access" ON public.lipa_mdogo_mdogo FOR ALL USING (true);
